/***
 * EPSWave's own instrument file: a `.epswave`, which is JSON.
 *
 * WHY A FORMAT OF OUR OWN WHEN .EFE ALREADY EXISTS
 *
 * An .EFE is the EPS's memory image, and writing one means reproducing the
 * EPS's allocator: where each object sits, how much slack is left after it, and
 * five words of bookkeeping per object of which two are linked list pointers
 * whose rules are not yet known. Reading one needs none of that, which is why
 * reading came first and works.
 *
 * This format needs none of it either, because it stores what actually matters
 * and nothing else:
 *
 *   the raw parameter blocks, word for word, exactly as they came off the wire
 *   the audio, sample for sample
 *
 * Those are the two things a restore sends. Everything else in an .EFE —
 * offsets, block sizes, list links — describes where the EPS happened to put
 * things in RAM at the moment of the dump, and is regenerated by the synth on
 * the way back in. See "Restoring, and the one sharp edge" in METHODS.md.
 *
 * So this is a lossless record of an instrument that can be written today, and
 * an .EFE can be generated from it later without going near the synth again.
 * That ordering is deliberate: the twenty minute part is reading the audio off
 * the hardware, and it should not have to be repeated because the container was
 * decided wrongly.
 *
 * NOTHING IS INTERPRETED ON THE WAY IN OR OUT. The blocks are stored whole,
 * including the words this program does not decode — the envelopes, the
 * modulation routings, the words the specification calls unused. A backup taken
 * today keeps everything, including whatever turns out to matter later.
 *
 * The decoded fields that sit alongside them are for reading by eye and for
 * anything else that wants to consume these files. They are written from the
 * blocks and, on the way back in, are recomputed from the blocks rather than
 * trusted, so an edited file cannot disagree with itself.
 */
class EPSWaveFile {

    static FORMAT = "epswave-instrument"
    static VERSION = 1
    static EXTENSION = ".epswave"

    /***
     * Words as hexadecimal, four characters each, no separators.
     *
     * A parameter block is at most 323 words, so this is at most 1292
     * characters and there is nothing to gain from packing it further. Hex
     * keeps a block greppable and diffable, and keeps the word offsets the
     * specification prints countable by eye: word 25 of the instrument is
     * characters 100 to 103.
     */
    static toHex(words){
        let out = ""
        for(let i = 0; i < words.length; i++){
            out += (words[i] & 0xFFFF).toString(16).padStart(4, "0")
        }
        return out
    }

    static fromHex(hex, expected){
        const text = String(hex || "").trim()
        if(text.length % 4 != 0){
            throw new Error(`Corrupt block: ${text.length} hex characters is not a whole `
                + "number of 16 bit words")
        }
        const words = []
        for(let i = 0; i < text.length; i += 4){
            const word = parseInt(text.substr(i, 4), 16)
            if(isNaN(word)) throw new Error("Corrupt block: not hexadecimal")
            words.push(word)
        }
        // Length is checked because the whole point of the blocks is that they
        // go back to the synth unaltered, and a block of the wrong length is
        // the one mistake that would be sent rather than caught. This is the
        // same failure that once offered the EPS the rest of a disk image.
        if(expected !== undefined && words.length != expected){
            throw new Error(`Corrupt block: ${words.length} words where ${expected} `
                + "were expected")
        }
        return words
    }

    /***
     * Audio as base64 of little endian 16 bit samples.
     *
     * Little endian because that is what a WAV holds and what every tool that
     * might open one of these expects, even though the EPS itself is big endian
     * on the wire. The conversion belongs at the edge, once, rather than in
     * everything that reads the file.
     *
     * Chunked because String.fromCharCode(...bytes) on a two million sample
     * wavesample overflows the argument stack, which is a crash rather than a
     * slow path.
     */
    static CHUNK = 0x8000

    static encodeAudio(samples){
        const bytes = new Uint8Array(samples.length * 2)
        for(let i = 0; i < samples.length; i++){
            const value = samples[i] & 0xFFFF
            bytes[i * 2] = value & 0xFF
            bytes[i * 2 + 1] = (value >> 8) & 0xFF
        }
        let binary = ""
        for(let at = 0; at < bytes.length; at += EPSWaveFile.CHUNK){
            binary += String.fromCharCode(...bytes.subarray(at, at + EPSWaveFile.CHUNK))
        }
        return btoa(binary)
    }

    static decodeAudio(base64){
        const binary = atob(String(base64 || ""))
        const samples = new Int16Array(binary.length >> 1)
        for(let i = 0; i < samples.length; i++){
            const value = binary.charCodeAt(i * 2) | (binary.charCodeAt(i * 2 + 1) << 8)
            samples[i] = value > 0x7FFF ? value - 0x10000 : value
        }
        return samples
    }

    /***
     * Writes an inventory and its audio out as the text of a `.epswave` file.
     *
     * `audio` is a Map from wavesample number to samples, which is what
     * downloadAudio returns; a wavesample with no entry is written without
     * audio rather than refused, so a partial backup can still be saved.
     *
     * A copy's audio is not stored. Section 7.3 word 12 says which wavesample
     * holds it, and writing it again under a second name would double the size
     * of every split that shares a sample between zones.
     */
    static write(inventory, audio = new Map(), meta = {}){
        const instrument = inventory.instrument
        const layerNumber = inventory.layers.length ? inventory.layers[0].number : 0
        return JSON.stringify({
            format: EPSWaveFile.FORMAT,
            version: EPSWaveFile.VERSION,
            tool: meta.tool || "EPSWave",
            created: meta.created || new Date().toISOString(),
            // Where this came from, for the person reading the file in a year.
            // Not used on the way back in.
            source: meta.source || inventory.source || "unknown",
            sourceName: meta.sourceName
                || (inventory.file ? inventory.file.fileName || inventory.file.name : ""),
            instrument: {
                name: instrument.name,
                isEps16Plus: instrument.isEps16Plus,
                keyRangeLo: instrument.keyRangeLo,
                keyRangeHi: instrument.keyRangeHi,
                transpose: instrument.transpose,
                words: EPSWaveFile.toHex(instrument.words)
            },
            layers: inventory.layers.map(layer => ({
                number: layer.number,
                name: layer.name,
                velocityLo: layer.velocityLo,
                velocityHi: layer.velocityHi,
                words: EPSWaveFile.toHex(layer.words)
            })),
            wavesamples: inventory.wavesamples.map(ws => ({
                number: ws.number,
                name: ws.name,
                layer: ws.layer == null ? layerNumber : ws.layer,
                copyOf: ws.isCopy ? ws.copyNumber : 0,
                keyRangeLo: ws.keyRangeLo,
                keyRangeHi: ws.keyRangeHi,
                rootKey: ws.rootKey,
                sampleRateHz: ws.sampleRateHz,
                samples: ws.sampleEnd,
                words: EPSWaveFile.toHex(ws.words),
                audio: !ws.isCopy && audio.has(ws.number)
                    ? EPSWaveFile.encodeAudio(audio.get(ws.number)) : null
            })),
            // Whatever was learned about the effect, which is a name from a
            // disk file and a handful of numbers over MIDI. Kept because it
            // cannot be sent to the synth and therefore has to be read by a
            // human off this file.
            effect: inventory.effect || null
        }, null, 1)
    }

    /***
     * Reads one back, into the shape getInstrumentInventory and
     * EPSEfe.readInstrument both return, so the page renders it and
     * uploadInstrument sends it without knowing where it came from.
     *
     * Every decoded field is recomputed from the stored blocks. The ones
     * written alongside them are ignored entirely: if someone edits the JSON by
     * hand, what reaches the synth is the block, so the block is what has to be
     * believed.
     */
    static read(text){
        let file
        try{
            file = JSON.parse(text)
        }catch(error){
            throw new Error("This is not a readable .epswave file: " + error.message)
        }
        if(!file || file.format != EPSWaveFile.FORMAT){
            throw new Error("This is not an EPSWave instrument file"
                + (file && file.format ? `: it says it is "${file.format}"` : ""))
        }
        if(!(file.version <= EPSWaveFile.VERSION)){
            throw new Error(`This file is version ${file.version} and this is EPSWave `
                + `${EPSWaveFile.VERSION}. Update EPSWave to open it.`)
        }

        const instWords = EPSWaveFile.fromHex(file.instrument && file.instrument.words,
            EPSBlocks.INSTRUMENT_BLOCK_WORDS)
        const instrument = { ...EPSBlocks.decodeInstrument(instWords), words: instWords }

        const layers = (file.layers || []).map(layer => {
            const words = EPSWaveFile.fromHex(layer.words, EPSBlocks.LAYER_BLOCK_WORDS)
            return { ...EPSBlocks.decodeLayer(words), number: layer.number, words }
        })

        const audio = new Map()
        const wavesamples = (file.wavesamples || []).map(entry => {
            const words = EPSWaveFile.fromHex(entry.words, EPSBlocks.WAVESAMPLE_BLOCK_WORDS)
            const ws = EPSBlocks.decodeWavesample(words)
            if(entry.audio) audio.set(entry.number, EPSWaveFile.decodeAudio(entry.audio))
            return { ...ws, number: entry.number, words,
                layer: entry.layer == null ? null : entry.layer,
                sampleRateHz: WaveGen.rateFromCode(ws.sampleRateCode) }
        })

        // Copies are served from whatever holds their samples, the same rule
        // the disk reader follows, so every wavesample that sounds has audio to
        // hand however the instrument was put together.
        for(const ws of wavesamples.filter(w => w.isCopy)){
            let at = ws
            for(let hop = 0; at.isCopy && hop <= EPSBlocks.WAVESAMPLE_COUNT; hop++){
                const source = wavesamples.find(w => w.number == at.copyNumber)
                if(!source) break
                at = source
            }
            if(!at.isCopy && audio.has(at.number)) audio.set(ws.number, audio.get(at.number))
        }

        const audioSamples = wavesamples.filter(ws => !ws.isCopy)
            .reduce((sum, ws) => sum + ws.sampleEnd, 0)

        return { source: "epswave", file, instrument, layers, wavesamples, audio,
            audioSamples, wireBytes: audioSamples * 3, effect: file.effect || null }
    }
}

// Node runs the tests; the browser gets the class from the script tag.
if(typeof module != 'undefined' && module.exports) module.exports = EPSWaveFile
